name: Deploy ADF
on:
  workflow_dispatch:
jobs:
   Azure-Login:
     runs-on: ubuntu-latest
     steps:
     #Checkout code
       - uses: actions/checkout@main
        
     # Log into Azure
       - uses: azure/login@v1
         with:
           creds: ${{ secrets.AZURE_CREDENTIALS }}
   calling-workflow:
     needs: Azure-Login 
     uses: SamaRamya/AzureDataFactory/.github/workflows/inputfile.yml@main
   
   ARM-Template-deployment:
     needs: calling-workflow 
     runs-on: ubuntu-latest
     steps:
      - uses: azure/arm-deploy@v1
        with:
          resourceGroupName: ${{ needs.calling-workflow.outputs.resourceGroupName }}
          template: ${{ needs.calling-workflow.outputs.resourceGroupName }}
          deploymentMode: Incremental
          parameters: factoryName=adfv2-cicd-target
        
  
             
