name: Deploy ADF
on:
  workflow_dispatch:
jobs:
   Azure-Login:
     runs-on: ubuntu-latest
     steps:
     #Checkout code
       - uses: actions/checkout@main
        
     # Log into Azure
       - uses: azure/login@v1
         with:
           creds: ${{ secrets.AZURE_CREDENTIALS }}
   calling-workflow:
     needs: Azure-Login 
     uses: SamaRamya/AzureDataFactory/.github/workflows/inputfile.yml@main
   
   ARM-Template-deployment:
     needs: calling-workflow 
     runs-on: ubuntu-latest
     steps:
      - uses: Azure/data-factory-deploy-action@v1.2.0
        with:
          resourceGroupName: ${{ needs.calling-workflow.outputs.resourceGroupName }}
          armTemplateFile: ${{ needs.calling-workflow.outputs.armTemplateFile }}
          armTemplateParametersFile: ${{ needs.calling-workflow.outputs.armTemplateParametersFile }} 
          dataFactoryName: ${{ needs.calling-workflow.outputs.dataFactoryName }} 
  
             
