name: Deploy ADF
on:
  workflow_dispatch:
jobs:
  uses: SamaRamya/AzureDataFactory/.github/workflows/inputfile.yml@main
  job1:
    - name: Run Pre-deployment script
      runs-on: ubuntu-latest
      run: |
        ${{ github.action_path }}/PrePostDeploymentScript.ps1 
          -armTemplate "${{ inputs.armTemplateFile }}" 
          -ResourceGroupName "${{ inputs.resourceGroupName }}" 
          -DataFactoryName "${{ inputs.dataFactoryName }}" 
          -predeployment $true 
          -deleteDeployment $false
      shell: pwsh
  job2:
    - name: Run ARM deploy
      uses: azure/arm-deploy@v1
      with:
        resourceGroupName: ${{ inputs.resourceGroupName }}
        template: ${{ inputs.armTemplateFile }}
        parameters: ${{ inputs.armTemplateParametersFile }} factoryName=${{ inputs.dataFactoryName }} ${{ inputs.additionalParameters }}
  job3:
     - name: Run Post-deployment script
       run: |
         ${{ github.action_path }}/PrePostDeploymentScript.ps1 
          -armTemplate "${{ inputs.armTemplateFile }}" 
          -ResourceGroupName "${{ inputs.resourceGroupName }}" 
          -DataFactoryName '${{ inputs.dataFactoryName }}' 
          -predeployment $false 
          -deleteDeployment $true
       shell: pwsh
