name: Deploy ADF
on:
  workflow_dispatch:
jobs:
  job:
    uses: SamaRamya/AzureDataFactory/.github/workflows/inputfile.yml@main
  job1:
      runs-on: ubuntu-latest
      steps:
        - name: Run Pre-deployment script
          shell: pwsh
          run: |
            invoke-webrequest -Uri "https://raw.githubusercontent.com/SamaRamya/AzureDataFactory/main/.github/workflows/PrePostDeploymentScript.ps1" -OutFile "PrePostDeploymentScript.ps1"
             ./PrePostDeploymentScript.ps1 -armTemplate "${{ needs.job.outputs.armTemplateFile }}" -ResourceGroupName "${{ needs.job.outputs.resourceGroupName }}" -DataFactoryName '${{ needs.job.outputs.dataFactoryName }}' -predeployment $false -deleteDeployment $true
           
        - name: Run ARM deploy
          uses: azure/arm-deploy@v1
          with:
            resourceGroupName: ${{ .resourceGroupName }}
            template: ${{ needs.job.outputs.armTemplateFile }}
            parameters: ${{ needs.job.outputs.armTemplateParametersFile }} factoryName=${{ needs.job.outputs.dataFactoryName }} ${{ needs.job.outputs.additionalParameters }}
  
        - name: Run Post-deployment script
          shell: pwsh
          run: |
             invoke-webrequest -Uri "https://raw.githubusercontent.com/SamaRamya/AzureDataFactory/main/.github/workflows/PrePostDeploymentScript.ps1" -OutFile "PrePostDeploymentScript.ps1"
             ./PrePostDeploymentScript.ps1 -armTemplate "${{ needs.job.outputs.armTemplateFile }}" -ResourceGroupName "${{ needs.job.outputs.resourceGroupName }}" -DataFactoryName '${{ needs.job.outputs.dataFactoryName }}' -predeployment $false -deleteDeployment $true
             
             
      
