name: Deploy ADF
on:
  workflow_dispatch:
jobs:
  job:
    uses: SamaRamya/AzureDataFactory/.github/workflows/inputfile.yml@main
  job1:
      runs-on: ubuntu-latest
      steps:
        - name: Stop Active Triggers
          shell: pwsh
          run: |
            Stop-AzDataFactoryV2Trigger - ResourceGroupName "${{ needs.job.outputs.ResourceGroupName }}" -DataFactoryName "${{ needs.job.outputs.dataFactoryName }}" -TriggerName " " 
            
        - name: ARM Template deploy
          uses: azure/arm-deploy@v1
          with:
            resourceGroupName: ${{ needs.job.outputs.resourceGroupName }}
            template: ${{ needs.job.outputs.armTemplateFile }}
            parameters: ${{ needs.job.outputs.armTemplateParametersFile }} 
            factoryName: ${{ needs.job.outputs.dataFactoryName }} 
  
        - name: Resource Cleanup(pipeline)
          shell: pwsh
          run: |
             Get-AzDataFactoryPipeline -ResourceGroupName "${{ needs.job.outputs.resourceGroupName }}" -DataFactoryName "${{ needs.job.outputs.dataFactoryName }}" -PipelineName ""
             Remove-AzDataFactoryV2Pipeline -ResourceGroupName "${{ needs.job.outputs.resourceGroupName }}" -DataFactoryName "${{ needs.job.outputs.dataFactoryName }}" -PipelineName ""
             
        - name: Resource Cleanup(DataFlows)
          shell: pwsh
          run: |
             Get-AzDataFactoryV2DataFlow -ResourceGroupName "${{ needs.job.outputs.resourceGroupName }}" -DataFactoryName "${{ needs.job.outputs.dataFactoryName }}" -DataFlowName ""
             Remove-AzDataFactoryV2DataFlow -ResourceGroupName "${{ needs.job.outputs.resourceGroupName }}" -DataFactoryName "${{ needs.job.outputs.dataFactoryName }}" -DataFlowName ""
             
        - name: Resource Cleanup(Datasets)
          shell: pwsh
          run: |
             Get-AzDataFactoryV2Dataset -ResourceGroupName "${{ needs.job.outputs.resourceGroupName }}" -DataFactoryName "${{ needs.job.outputs.dataFactoryName }}" -Dataset ""
             Remove-AzDataFactoryV2Dataset -ResourceGroupName "${{ needs.job.outputs.resourceGroupName }}" -DataFactoryName "${{ needs.job.outputs.dataFactoryName }}" -Dataset ""
             
        - name: Resource Cleanup(Linked Services)
          shell: pwsh
          run: |
             Get-AzDataFactoryLinkedService -ResourceGroupName "${{ needs.job.outputs.resourceGroupName }}" -DataFactoryName "${{ needs.job.outputs.dataFactoryName }}" -DataFlowName ""
             Remove-AzDataFactoryV2LinkedService -ResourceGroupName "${{ needs.job.outputs.resourceGroupName }}" -DataFactoryName "${{ needs.job.outputs.dataFactoryName }}" -DataFlowName ""
             
        - name: Restart Active Triggers
          shell: pwsh
          run: |
            Start-AzDataFactoryV2Trigger - ResourceGroupName "${{ needs.job.outputs.resourceGroupName }}" -DataFactoryName "${{ needs.job.outputs.dataFactoryName }}" -TriggerName " " 
             
         
             
             
             
             
