name: InputFile
on:
  workflow_call:
    inputs:
      resourceGroupName:
        description: 'Data Factory resource group name'
        required: true
        type: string
      dataFactoryName:
        description: 'Data factory name'
        required: true
        type: string
      armTemplateFile:
        description: 'ARM template file name'
        required: true
        type: string
      armTemplateParametersFile:
       description: 'ARM template parameters file name'
       required: true
       type: string
      additionalParameters:
       description: 'Parameters which will be replaced in the ARM template'
       required: false
       type: string
       default: ''
      skipAzModuleInstallation:
        description: 'Parameters which skip the Az module installation'
        required: false
        default: 'false'
        type: string
        
jobs:
 Inputs:
   runs-on: ubuntu-latest
   steps:
     - run: echo "Inputs"
    
  

